/**
 * TODO:
 * Ideal API data example
 */

// {
//   name: 'Wolverhampton Wanderers',
//   nickname: 'Wolves',
//   overall_league_position: '1',
//   overall_league_played: '43',
//   overall_league_W: '29',
//   overall_league_D: '8',
//   overall_league_L: '6',
//   overall_league_GF: '78',
//   overall_league_GA: '36',
//   overall_league_PTS: '95',
//   home_league_W: '16',
//   home_league_D: '4',
//   home_league_L: '2',
//   home_league_GF: '47',
//   home_league_GA: '18',
//   away_league_W: '13',
//   away_league_D: '4',
//   away_league_L: '4',
//   away_league_GF: '31',
//   away_league_GA: '18',
// }

const mockData = {
  teams: [
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Wolverhampton Wanderers',
      overall_league_position: '1',
      overall_league_payed: '43',
      overall_league_W: '29',
      overall_league_D: '8',
      overall_league_L: '6',
      overall_league_GF: '78',
      overall_league_GA: '36',
      overall_league_PTS: '95',
      home_league_position: '1',
      home_league_payed: '22',
      home_league_W: '16',
      home_league_D: '4',
      home_league_L: '2',
      home_league_GF: '47',
      home_league_GA: '18',
      home_league_PTS: '52',
      away_league_position: '1',
      away_league_payed: '21',
      away_league_W: '13',
      away_league_D: '4',
      away_league_L: '4',
      away_league_GF: '31',
      away_league_GA: '18',
      away_league_PTS: '43'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Fulham',
      overall_league_position: '3',
      overall_league_payed: '43',
      overall_league_W: '23',
      overall_league_D: '13',
      overall_league_L: '7',
      overall_league_GF: '73',
      overall_league_GA: '42',
      overall_league_PTS: '82',
      home_league_position: '4',
      home_league_payed: '22',
      home_league_W: '12',
      home_league_D: '8',
      home_league_L: '2',
      home_league_GF: '38',
      home_league_GA: '16',
      home_league_PTS: '44',
      away_league_position: '2',
      away_league_payed: '21',
      away_league_W: '11',
      away_league_D: '5',
      away_league_L: '5',
      away_league_GF: '35',
      away_league_GA: '26',
      away_league_PTS: '38'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Cardiff City',
      overall_league_position: '2',
      overall_league_payed: '42',
      overall_league_W: '25',
      overall_league_D: '8',
      overall_league_L: '9',
      overall_league_GF: '64',
      overall_league_GA: '35',
      overall_league_PTS: '83',
      home_league_position: '3',
      home_league_payed: '21',
      home_league_W: '15',
      home_league_D: '3',
      home_league_L: '3',
      home_league_GF: '38',
      home_league_GA: '15',
      home_league_PTS: '48',
      away_league_position: '3',
      away_league_payed: '21',
      away_league_W: '10',
      away_league_D: '5',
      away_league_L: '6',
      away_league_GF: '26',
      away_league_GA: '20',
      away_league_PTS: '35'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Preston North End',
      overall_league_position: '8',
      overall_league_payed: '43',
      overall_league_W: '17',
      overall_league_D: '15',
      overall_league_L: '11',
      overall_league_GF: '54',
      overall_league_GA: '45',
      overall_league_PTS: '66',
      home_league_position: '13',
      home_league_payed: '21',
      home_league_W: '8',
      home_league_D: '7',
      home_league_L: '6',
      home_league_GF: '25',
      home_league_GA: '21',
      home_league_PTS: '31',
      away_league_position: '4',
      away_league_payed: '22',
      away_league_W: '9',
      away_league_D: '8',
      away_league_L: '5',
      away_league_GF: '29',
      away_league_GA: '24',
      away_league_PTS: '35'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Derby County',
      overall_league_position: '7',
      overall_league_payed: '42',
      overall_league_W: '18',
      overall_league_D: '14',
      overall_league_L: '10',
      overall_league_GF: '61',
      overall_league_GA: '43',
      overall_league_PTS: '68',
      home_league_position: '10',
      home_league_payed: '20',
      home_league_W: '10',
      home_league_D: '5',
      home_league_L: '5',
      home_league_GF: '33',
      home_league_GA: '18',
      home_league_PTS: '35',
      away_league_position: '5',
      away_league_payed: '22',
      away_league_W: '8',
      away_league_D: '9',
      away_league_L: '5',
      away_league_GF: '28',
      away_league_GA: '25',
      away_league_PTS: '33'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Aston Villa',
      overall_league_position: '4',
      overall_league_payed: '43',
      overall_league_W: '23',
      overall_league_D: '10',
      overall_league_L: '10',
      overall_league_GF: '67',
      overall_league_GA: '40',
      overall_league_PTS: '79',
      home_league_position: '2',
      home_league_payed: '22',
      home_league_W: '14',
      home_league_D: '6',
      home_league_L: '2',
      home_league_GF: '41',
      home_league_GA: '18',
      home_league_PTS: '48',
      away_league_position: '6',
      away_league_payed: '21',
      away_league_W: '9',
      away_league_D: '4',
      away_league_L: '8',
      away_league_GF: '26',
      away_league_GA: '22',
      away_league_PTS: '31'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Brentford',
      overall_league_position: '10',
      overall_league_payed: '43',
      overall_league_W: '17',
      overall_league_D: '14',
      overall_league_L: '12',
      overall_league_GF: '59',
      overall_league_GA: '48',
      overall_league_PTS: '65',
      home_league_position: '11',
      home_league_payed: '21',
      home_league_W: '8',
      home_league_D: '10',
      home_league_L: '3',
      home_league_GF: '34',
      home_league_GA: '22',
      home_league_PTS: '34',
      away_league_position: '7',
      away_league_payed: '22',
      away_league_W: '9',
      away_league_D: '4',
      away_league_L: '9',
      away_league_GF: '25',
      away_league_GA: '26',
      away_league_PTS: '31'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Millwall',
      overall_league_position: '6',
      overall_league_payed: '43',
      overall_league_W: '18',
      overall_league_D: '15',
      overall_league_L: '10',
      overall_league_GF: '55',
      overall_league_GA: '40',
      overall_league_PTS: '69',
      home_league_position: '7',
      home_league_payed: '21',
      home_league_W: '11',
      home_league_D: '7',
      home_league_L: '3',
      home_league_GF: '32',
      home_league_GA: '18',
      home_league_PTS: '40',
      away_league_position: '8',
      away_league_payed: '22',
      away_league_W: '7',
      away_league_D: '8',
      away_league_L: '7',
      away_league_GF: '23',
      away_league_GA: '22',
      away_league_PTS: '29'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Middlesbrough',
      overall_league_position: '5',
      overall_league_payed: '43',
      overall_league_W: '20',
      overall_league_D: '9',
      overall_league_L: '14',
      overall_league_GF: '61',
      overall_league_GA: '42',
      overall_league_PTS: '69',
      home_league_position: '5',
      home_league_payed: '22',
      home_league_W: '13',
      home_league_D: '3',
      home_league_L: '6',
      home_league_GF: '31',
      home_league_GA: '17',
      home_league_PTS: '42',
      away_league_position: '9',
      away_league_payed: '21',
      away_league_W: '7',
      away_league_D: '6',
      away_league_L: '8',
      away_league_GF: '30',
      away_league_GA: '25',
      away_league_PTS: '27'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Bristol City',
      overall_league_position: '11',
      overall_league_payed: '43',
      overall_league_W: '17',
      overall_league_D: '14',
      overall_league_L: '12',
      overall_league_GF: '60',
      overall_league_GA: '50',
      overall_league_PTS: '65',
      home_league_position: '8',
      home_league_payed: '21',
      home_league_W: '11',
      home_league_D: '5',
      home_league_L: '5',
      home_league_GF: '34',
      home_league_GA: '20',
      home_league_PTS: '38',
      away_league_position: '10',
      away_league_payed: '22',
      away_league_W: '6',
      away_league_D: '9',
      away_league_L: '7',
      away_league_GF: '26',
      away_league_GA: '30',
      away_league_PTS: '27'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Norwich City',
      overall_league_position: '13',
      overall_league_payed: '43',
      overall_league_W: '14',
      overall_league_D: '14',
      overall_league_L: '15',
      overall_league_GF: '46',
      overall_league_GA: '54',
      overall_league_PTS: '56',
      home_league_position: '16',
      home_league_payed: '22',
      home_league_W: '7',
      home_league_D: '8',
      home_league_L: '7',
      home_league_GF: '23',
      home_league_GA: '24',
      home_league_PTS: '29',
      away_league_position: '11',
      away_league_payed: '21',
      away_league_W: '7',
      away_league_D: '6',
      away_league_L: '8',
      away_league_GF: '23',
      away_league_GA: '30',
      away_league_PTS: '27'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Sheffield United',
      overall_league_position: '9',
      overall_league_payed: '43',
      overall_league_W: '19',
      overall_league_D: '9',
      overall_league_L: '15',
      overall_league_GF: '58',
      overall_league_GA: '50',
      overall_league_PTS: '66',
      home_league_position: '6',
      home_league_payed: '22',
      home_league_W: '12',
      home_league_D: '5',
      home_league_L: '5',
      home_league_GF: '33',
      home_league_GA: '19',
      home_league_PTS: '41',
      away_league_position: '12',
      away_league_payed: '21',
      away_league_W: '7',
      away_league_D: '4',
      away_league_L: '10',
      away_league_GF: '25',
      away_league_GA: '31',
      away_league_PTS: '25'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Sheffield Wednesday',
      overall_league_position: '16',
      overall_league_payed: '43',
      overall_league_W: '12',
      overall_league_D: '14',
      overall_league_L: '17',
      overall_league_GF: '51',
      overall_league_GA: '59',
      overall_league_PTS: '50',
      home_league_position: '20',
      home_league_payed: '21',
      home_league_W: '6',
      home_league_D: '7',
      home_league_L: '8',
      home_league_GF: '29',
      home_league_GA: '30',
      home_league_PTS: '25',
      away_league_position: '13',
      away_league_payed: '22',
      away_league_W: '6',
      away_league_D: '7',
      away_league_L: '9',
      away_league_GF: '22',
      away_league_GA: '29',
      away_league_PTS: '25'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Leeds United',
      overall_league_position: '14',
      overall_league_payed: '43',
      overall_league_W: '15',
      overall_league_D: '9',
      overall_league_L: '19',
      overall_league_GF: '54',
      overall_league_GA: '61',
      overall_league_PTS: '54',
      home_league_position: '14',
      home_league_payed: '21',
      home_league_W: '8',
      home_league_D: '6',
      home_league_L: '7',
      home_league_GF: '28',
      home_league_GA: '26',
      home_league_PTS: '30',
      away_league_position: '14',
      away_league_payed: '22',
      away_league_W: '7',
      away_league_D: '3',
      away_league_L: '12',
      away_league_GF: '26',
      away_league_GA: '35',
      away_league_PTS: '24'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Ipswich Town',
      overall_league_position: '12',
      overall_league_payed: '43',
      overall_league_W: '16',
      overall_league_D: '8',
      overall_league_L: '19',
      overall_league_GF: '51',
      overall_league_GA: '54',
      overall_league_PTS: '56',
      home_league_position: '12',
      home_league_payed: '21',
      home_league_W: '9',
      home_league_D: '5',
      home_league_L: '7',
      home_league_GF: '27',
      home_league_GA: '21',
      home_league_PTS: '32',
      away_league_position: '15',
      away_league_payed: '22',
      away_league_W: '7',
      away_league_D: '3',
      away_league_L: '12',
      away_league_GF: '24',
      away_league_GA: '33',
      away_league_PTS: '24'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Sunderland',
      overall_league_position: '24',
      overall_league_payed: '43',
      overall_league_W: '6',
      overall_league_D: '16',
      overall_league_L: '21',
      overall_league_GF: '47',
      overall_league_GA: '76',
      overall_league_PTS: '34',
      home_league_position: '24',
      home_league_payed: '21',
      home_league_W: '2',
      home_league_D: '7',
      home_league_L: '12',
      home_league_GF: '19',
      home_league_GA: '37',
      home_league_PTS: '13',
      away_league_position: '16',
      away_league_payed: '22',
      away_league_W: '4',
      away_league_D: '9',
      away_league_L: '9',
      away_league_GF: '28',
      away_league_GA: '39',
      away_league_PTS: '21'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Burton Albion',
      overall_league_position: '23',
      overall_league_payed: '43',
      overall_league_W: '8',
      overall_league_D: '11',
      overall_league_L: '24',
      overall_league_GF: '33',
      overall_league_GA: '78',
      overall_league_PTS: '35',
      home_league_position: '23',
      home_league_payed: '22',
      home_league_W: '3',
      home_league_D: '5',
      home_league_L: '14',
      home_league_GF: '17',
      home_league_GA: '43',
      home_league_PTS: '14',
      away_league_position: '17',
      away_league_payed: '21',
      away_league_W: '5',
      away_league_D: '6',
      away_league_L: '10',
      away_league_GF: '16',
      away_league_GA: '35',
      away_league_PTS: '21'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Reading',
      overall_league_position: '19',
      overall_league_payed: '43',
      overall_league_W: '10',
      overall_league_D: '13',
      overall_league_L: '20',
      overall_league_GF: '48',
      overall_league_GA: '63',
      overall_league_PTS: '43',
      home_league_position: '21',
      home_league_payed: '22',
      home_league_W: '5',
      home_league_D: '8',
      home_league_L: '9',
      home_league_GF: '25',
      home_league_GA: '31',
      home_league_PTS: '23',
      away_league_position: '18',
      away_league_payed: '21',
      away_league_W: '5',
      away_league_D: '5',
      away_league_L: '11',
      away_league_GF: '23',
      away_league_GA: '32',
      away_league_PTS: '20'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Nottingham Forest',
      overall_league_position: '17',
      overall_league_payed: '42',
      overall_league_W: '14',
      overall_league_D: '7',
      overall_league_L: '21',
      overall_league_GF: '45',
      overall_league_GA: '60',
      overall_league_PTS: '49',
      home_league_position: '17',
      home_league_payed: '21',
      home_league_W: '9',
      home_league_D: '2',
      home_league_L: '10',
      home_league_GF: '22',
      home_league_GA: '27',
      home_league_PTS: '29',
      away_league_position: '19',
      away_league_payed: '21',
      away_league_W: '5',
      away_league_D: '5',
      away_league_L: '11',
      away_league_GF: '23',
      away_league_GA: '33',
      away_league_PTS: '20'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Hull City',
      overall_league_position: '18',
      overall_league_payed: '43',
      overall_league_W: '11',
      overall_league_D: '14',
      overall_league_L: '18',
      overall_league_GF: '64',
      overall_league_GA: '62',
      overall_league_PTS: '47',
      home_league_position: '15',
      home_league_payed: '22',
      home_league_W: '7',
      home_league_D: '8',
      home_league_L: '7',
      home_league_GF: '41',
      home_league_GA: '30',
      home_league_PTS: '29',
      away_league_position: '20',
      away_league_payed: '21',
      away_league_W: '4',
      away_league_D: '6',
      away_league_L: '11',
      away_league_GF: '23',
      away_league_GA: '32',
      away_league_PTS: '18'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Barnsley',
      overall_league_position: '22',
      overall_league_payed: '42',
      overall_league_W: '8',
      overall_league_D: '14',
      overall_league_L: '20',
      overall_league_GF: '44',
      overall_league_GA: '63',
      overall_league_PTS: '38',
      home_league_position: '22',
      home_league_payed: '22',
      home_league_W: '4',
      home_league_D: '9',
      home_league_L: '9',
      home_league_GF: '23',
      home_league_GA: '32',
      home_league_PTS: '21',
      away_league_position: '21',
      away_league_payed: '20',
      away_league_W: '4',
      away_league_D: '5',
      away_league_L: '11',
      away_league_GF: '21',
      away_league_GA: '31',
      away_league_PTS: '17'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Queens Park Rangers',
      overall_league_position: '15',
      overall_league_payed: '43',
      overall_league_W: '14',
      overall_league_D: '11',
      overall_league_L: '18',
      overall_league_GF: '54',
      overall_league_GA: '65',
      overall_league_PTS: '53',
      home_league_position: '9',
      home_league_payed: '22',
      home_league_W: '11',
      home_league_D: '5',
      home_league_L: '6',
      home_league_GF: '35',
      home_league_GA: '30',
      home_league_PTS: '38',
      away_league_position: '22',
      away_league_payed: '21',
      away_league_W: '3',
      away_league_D: '6',
      away_league_L: '12',
      away_league_GF: '19',
      away_league_GA: '35',
      away_league_PTS: '15'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Birmingham City',
      overall_league_position: '21',
      overall_league_payed: '43',
      overall_league_W: '11',
      overall_league_D: '7',
      overall_league_L: '25',
      overall_league_GF: '32',
      overall_league_GA: '63',
      overall_league_PTS: '40',
      home_league_position: '19',
      home_league_payed: '21',
      home_league_W: '8',
      home_league_D: '3',
      home_league_L: '10',
      home_league_GF: '16',
      home_league_GA: '22',
      home_league_PTS: '27',
      away_league_position: '23',
      away_league_payed: '22',
      away_league_W: '3',
      away_league_D: '4',
      away_league_L: '15',
      away_league_GF: '16',
      away_league_GA: '41',
      away_league_PTS: '13'
    },
    {
      country_name: 'England',
      league_id: '63',
      league_name: 'Championship',
      team_name: 'Bolton Wanderers',
      overall_league_position: '20',
      overall_league_payed: '43',
      overall_league_W: '9',
      overall_league_D: '13',
      overall_league_L: '21',
      overall_league_GF: '36',
      overall_league_GA: '66',
      overall_league_PTS: '40',
      home_league_position: '18',
      home_league_payed: '21',
      home_league_W: '8',
      home_league_D: '4',
      home_league_L: '9',
      home_league_GF: '22',
      home_league_GA: '27',
      home_league_PTS: '28',
      away_league_position: '24',
      away_league_payed: '22',
      away_league_W: '1',
      away_league_D: '9',
      away_league_L: '12',
      away_league_GF: '14',
      away_league_GA: '39',
      away_league_PTS: '12'
    }
  ]
};

export default mockData;
